# Enable SPI & PMW3610 Trackball
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

# PMW3610 Sensor Options (Uncomment if needed)
# CONFIG_PMW3610_ALT_SWAP_XY=y
# CONFIG_PMW3610_ALT_INVERT_X=y
# CONFIG_PMW3610_ALT_INVERT_Y=y

# Bluetooth LE stability and signal boost
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Power management / Deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
